version: "3.8"

services:
  chatbot:
    image: migloz/cafbot:latest # o la imagen base que tengas
    container_name: cafbot
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - ./app:/app/app # 👈 MONTA TU CÓDIGO LOCAL
      - ./chroma_db:/app/chroma_db
      - ./indexar_documentos.py:/app/indexar_documentos.py # opcional
    restart: unless-stopped
